CREATE TABLE tblAddress (
	 PK INT IDENTITY(1,1) PRIMARY KEY
	,Line1 NVARCHAR(MAX) NOT NULL
	,Line2 NVARCHAR(MAX) 
	,City NVARCHAR(MAX) NOT NULL
	,RegionCode NVARCHAR(MAX) NOT NULL
	,PostalCode NVARCHAR(7) NOT NULL
	,CountryCode NVARCHAR(2) NOT NULL
)

CREATE TABLE tblContent (
	 PK INT IDENTITY(1,1) PRIMARY KEY
	,FormName NVARCHAR(255) NOT NULL UNIQUE
	,Content NVARCHAR(MAX) NOT NULL
	,ActiveFlag BIT DEFAULT 1
)

CREATE TABLE tblRobust (
	 PK INT IDENTITY(1,1) PRIMARY KEY
	,CreateTS DATETIME DEFAULT GETDATE() NOT NULL
	,FirstContact DATETIME
	,LastContact DATETIME
	,LastFormID INT FOREIGN KEY REFERENCES tblContent(PK)
	,UserActive BIT DEFAULT 1
	,DateInactive DATETIME
	,CustomerNotes NVARCHAR(MAX)
)

CREATE TABLE tblContact (
	 PK INT IDENTITY(1,1) PRIMARY KEY
	,eMail NVARCHAR(255) NOT NULL UNIQUE
	,LName NVARCHAR(MAX) NOT NULL
	,FNAME NVARCHAR(MAX)
	,PhonePrimary NVARCHAR(11) NOT NULL
	,PhoneSecond NVARCHAR(11)
	,AddressID INT FOREIGN KEY REFERENCES tblAddress(PK)
	,RobustID INT FOREIGN KEY REFERENCES tblRobust(PK)
	,ContactCount INT
)